# Generated by Django 3.1.7 on 2021-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20210606_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
